spring:
    application:
        name: eureka-service
        
server:
    port: 9000
    
security:
    basic:
        enabled: false

management:
    security:
        enabled: false

eureka:
  server:
    enableSelfPreservation: true
  client:
    registerWithEureka: false
    fetchRegistry: false
      