eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: https://commerce-discovery-server-clouded-milo.cfapps.io/eureka/
  instance:
    hostname: localhost