eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      #defaultZone: https://commerce-discovery-server-clouded-milo.cfapps.io/eureka/
      defaultZone: http://localhost:9000/eureka/
  instance:
    hostname: localhost