eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: https://commerce-discovery-server-clouded-milo.cfapps.io/eureka/
  instance:
    hostname: localhost
    
zuul:
  #Service will be mapped under the /api URI
  prefix: /xcommerce
  routes:
    user:
      path: /user/**
      serviceId: USER-SERVICE
    product:
      path: /product/**
      serviceId: PRODUCT-SERVICE
    cart:    
      path: /cart/**
      serviceId: CART-SERVICE
      